version: '3'
services:
  db:
    container_name: pg_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: receipt_db
    ports:
      - "5432:5432"
  app:
    container_name: receipt-pos-with-node
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/receipt_db
