version: '3'
services:
  app:
    build: .
    ports:
    - "3000:3000"
    depends_on:
      - postgres
    postgres:
      image: postgres
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pos
      ports:
        - "5432:5432"